spring:
    datasource:
        url:jdbc:h2:~/book;DB_CLOSE_ON_EXIT=FALSE
        username:sa
    jpa:
        hibernate:
            ddl-auto:update
    h2:
        console:
            enabled = true
            path: /h2-console
server:
    port:8080